spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/profiles
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  error:
    include-message: always
  port: 8080
bot:
  token: <provide your discord bot token here>
lavalink:
  server:
    sources:
      youtube: false